
-- TABLA CLIENTES

CREATE TABLE CLIENTES (
  DNI VARCHAR(9),
  NOMBRE VARCHAR(50) NOT NULL,
  APELLIDOS VARCHAR(50) NOT NULL,
  TELEFONO VARCHAR(9) NOT NULL,
  CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);

-- TABLA PATROCINADORES

CREATE TABLE PATROCINADORES (
  NOMBRE VARCHAR(50),	
  TOTAL_CARRERAS_PATROCINADAS DOUBLE PRECISION,
  TEMPORADA VARCHAR(10) NOT NULL,
  CONSTRAINT PK_PATROCINADORES PRIMARY KEY (NOMBRE)
);

-- TABLA APUESTAS

CREATE TABLE APUESTAS (
  CODIGO VARCHAR(10),
  IMPORTE_MAXIMO DOUBLE PRECISION,
  IMPORTE_MINIMO DOUBLE PRECISION,
  TANTO_A_UNO DOUBLE PRECISION,
  DNI_CLIENTE VARCHAR(9) NOT NULL,
  CODIGO_CARRERA DOUBLE PRECISION NOT NULL,
  NOMBRE_CABALLO VARCHAR(50) NOT NULL,
  CONSTRAINT PK_APUESTAS PRIMARY KEY (CODIGO),
  CONSTRAINT FK_APUESTAS_CLIENTES FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES (DNI),
  CONSTRAINT FK_APUESTAS_CARRERAS FOREIGN KEY (CODIGO_CARRERA) REFERENCES CARRERAS (CODIGO_CARRERA),
  CONSTRAINT FK_APUESTAS_CABALLOS FOREIGN KEY (NOMBRE_CABALLO) REFERENCES CABALLOS (NOMBRE)
);

-- TABLA ABONOS

CREATE TABLE ABONOS (
  DNI_CLIENTE VARCHAR(9),
  NUMERO_ZONA DOUBLE PRECISION,
  PRECIO DOUBLE PRECISION NOT NULL,
  CONSTRAINT PK_ABONOS PRIMARY KEY (DNI_CLIENTE, NUMERO_ZONA),
  CONSTRAINT FK_ABONOS_CLIENTES FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES (DNI),
  CONSTRAINT FK_ABONOS_ZONAS FOREIGN KEY (NUMERO_ZONA) REFERENCES ZONAS (NUMERO_ZONA)
);

-- TABLA ZONAS

CREATE TABLE ZONAS (
  NUMERO_ZONA DOUBLE PRECISION,
  LOCALIDAD VARCHAR(50) NOT NULL,
  CONSTRAINT PK_ZONAS PRIMARY KEY (NUMERO_ZONA)
);

-- TABLA ENTRADAS DIARIAS

CREATE TABLE ENTRADAS_DIARIAS (
  NUMERO_ZONA DOUBLE PRECISION,
  FECHA TIMESTAMP(0) NOT NULL,
  PRECIO DOUBLE PRECISION NOT NULL,
  NUMERO_VENTAS DOUBLE PRECISION,
  CONSTRAINT PK_ENTRADAS_DIARIAS PRIMARY KEY (NUMERO_ZONA, FECHA),
  CONSTRAINT FK_ENTRADAS_DIARIAS_ZONAS FOREIGN KEY (NUMERO_ZONA) REFERENCES ZONAS (NUMERO_ZONA)
);

-- TABLA CARRERA

CREATE TABLE CARRERAS (
  CODIGO_CARRERA DOUBLE PRECISION,
  FECHA TIMESTAMP(0) NOT NULL,
  HORA DOUBLE PRECISION NOT NULL,
  CABALLOS VARCHAR(50) NOT NULL,
  JOCKEYS VARCHAR(50) NOT NULL,
  NOMBRE_PATROCINADOR VARCHAR(50) NOT NULL,
  CONSTRAINT PK_CARRERAS PRIMARY KEY (CODIGO_CARRERA),
  CONSTRAINT FK_CARRERAS_PATROCINADORES FOREIGN KEY (NOMBRE_PATROCINADOR) REFERENCES PATROCINADORES (NOMBRE)
);

-- TABLA CUOTA PARTICIPACION

CREATE TABLE CUOTA_PARTICIPACION (
  NUMERO_FACTURA DOUBLE PRECISION,
  IMPORTE DOUBLE PRECISION,
  DNI_PARTICIPANTE VARCHAR(9) NOT NULL,
  CONSTRAINT PK_CUOTA_PARTICIPACION PRIMARY KEY (NUMERO_FACTURA),
  CONSTRAINT FK_CUOTA_PARt_PARTICI FOREIGN KEY (DNI_PARTICIPANTE) REFERENCES PARTICIPANTES (DNI)
);

-- TABLA PARTICIPANTES

CREATE TABLE participantes (
  DNI VARCHAR(10),
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  posicion SMALLINT NOT NULL,
  dorsal SMALLINT NOT NULL,
  CONSTRAINT PK_PARTICIPANTES PRIMARY KEY (DNI)
);


-- TABLA CABALLOS

CREATE TABLE caballos (
  nombre VARCHAR(50),
  peso DECIMAL(3,2) NOT NULL,
  propietario VARCHAR(50) NOT NULL,
  nacionalidad VARCHAR(50) NOT NULL,
  ID_trabajador INT NOT NULL,
  CONSTRAINT PK_CABALLOS PRIMARY KEY (nombre),
  CONSTRAINT FK_CABALLOS_PARTICIPANTES FOREIGN KEY (propietario) REFERENCES participantes (DNI),
  CONSTRAINT FK_CABALLOS_CUIDADORES FOREIGN KEY (ID_trabajador) REFERENCES cuidadores (ID)
);

-- TABLA CORREDORES

CREATE TABLE corredores (
  nombre VARCHAR(50),
  DNI_participante VARCHAR(10) NOT NULL,
  CONSTRAINT pk_corredores PRIMARY KEY (nombre),
  CONSTRAINT fk_corredores_participantes FOREIGN KEY (DNI_participante) REFERENCES participantes(DNI)
);

-- TABLA CUIDADORES

CREATE TABLE cuidadores (
  ID INT,
  nombre VARCHAR(50) NOT NULL,
  apellido VARCHAR(50) NOT NULL,
  direccion VARCHAR(100) NOT NULL,
  telefono VARCHAR(9) NOT NULL,
  CONSTRAINT PK_CUIDADORES PRIMARY KEY (ID)
);

-- TABLA BOXES

CREATE TABLE boxes (
  numero_del_box SMALLINT,
  ubicacion VARCHAR(50) NOT NULL,
  superficie DECIMAL(3,2) NOT NULL,
  nombre_del_caballo VARCHAR(50) NOT NULL,
  CONSTRAINT pk_boxes PRIMARY KEY (numero_del_box),
  CONSTRAINT fk_boxes_caballos FOREIGN KEY (nombre_del_caballo) REFERENCES caballos(nombre)
);

-- TABLA PISTAS

CREATE TABLE pistas (
  numero_de_pista SMALLINT,
  ubicacion VARCHAR(50) NOT NULL,
  superficie DECIMAL(3,2) NOT NULL,
  CONSTRAINT pk_pistas PRIMARY KEY (numero_de_pista)
);

-- TABLA USO PISTAS

CREATE TABLE uso_pistas (
  nombre_del_caballo VARCHAR(50),
  numero_de_pista SMALLINT NOT NULL,
  cuadrante VARCHAR(20) NOT NULL,
  CONSTRAINT pk_uso_pistas PRIMARY KEY (nombre_del_caballo, numero_de_pista),
  CONSTRAINT fk_uso_pistas_pistas FOREIGN KEY (numero_de_pista) REFERENCES pistas(numero_de_pista),
  CONSTRAINT fk_uso_pistas_caballos FOREIGN KEY (nombre_del_caballo) REFERENCES caballos(nombre)
);

-- TABLA ALIMENTOS

CREATE TABLE alimentos (
  tipo VARCHAR(50),
  cantidad DECIMAL(3,2) NOT NULL,
  fecha_caducidad TIMESTAMP(0) NOT NULL,
  precio DECIMAL(5,2) NOT NULL,
  CONSTRAINT pk_alimentos PRIMARY KEY (tipo)
);

-- TABLA MEDICINAS

CREATE TABLE medicinas (
  nombre VARCHAR(50),
  dosis DECIMAL(3,2) NOT NULL,
  precio DECIMAL(5,2) NOT NULL,
  CONSTRAINT pk_medicinas PRIMARY KEY (nombre)
);

-- TABLA GENERAN GASTOS

CREATE TABLE generan_gastos (
  nombre_del_caballo VARCHAR(50) NOT NULL,
  numero_de_factura INT,
  nombre_de_los_propietarios VARCHAR(50) NOT NULL,
  fecha TIMESTAMP(0) NOT NULL,
  CONSTRAINT pk_generan_gastos PRIMARY KEY (nombre_del_caballo, numero_de_factura),
  CONSTRAINT fk_gen_ga_cab FOREIGN KEY (nombre_del_caballo) REFERENCES caballos(nombre),
  CONSTRAINT fk_gen_gas_part FOREIGN KEY (nombre_de_los_propietarios) REFERENCES participantes(DNI)
);

